language: php
php:
  - 7.1
  
services:
  - mysql
  
before_script:
  - composer install --dev
  - mysql -e 'create database IF NOT EXISTS later_job;'
  - mysql later_job < create.sql
  
script: 
 - vendor/bin/phpunit --configuration config/travis.lib.xml
 - vendor/bin/phpunit --configuration config/travis.api.xml
