language: php
php:
  - 5.6
  - 5.7

services:
  - mysql
  
before_script:
  - composer install --dev
  - mysql -e 'create database IF NOT EXISTS later_job;'
  - mysql vouchernum < create.sql
  
script: 
 - vendor/bin/phpunit --configuration config/travis.lib.xml
 - vendor/bin/phpunit --configuration config/travis.api.xml
