language: php
php:
  - 5.4
  - 5.3

before_script:
  - composer install --dev
  - mysql -e 'create database IF NOT EXISTS later_job;'
  - ./vendor/bin/migrate.php app:install --path migrations --dsn mysql://root:@127.0.0.1/later_job?migration_table=migrations_data
  - ./vendor/bin/migrate.php app:build --path migrations --force --dsn mysql://root:@127.0.0.1/later_job?migration_table=migrations_data
  
script: vendor/bin/phpunit --configuration travis.xml
